import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import NavBar from "@/components/NavBar";
import GeneralInfo from "@/components/GeneralInfo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchBar />
        <div className="grid grid-cols-10">
          <div className="col-span-1">
            <NavBar />
          </div>
          <div className="col-span-7 mx-2">{children}</div>
          <div className="col-span-2 ">
            <GeneralInfo />
          </div>
        </div>
      </body>
    </html>
  );
}
