import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import NavBar from "@/components/NavBar";
import GeneralInfo from "@/components/GeneralInfo";
import { WebSocketProvider } from "@/context/WebSocketContext";
import LoginLogoutButton from "@/components/auth/LoginLogoutButton";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WebSocketProvider>
          <AuthProvider>
            <header className="border-b sticky top-0 z-50 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
              <div className="container mx-auto flex items-center justify-between px-6 py-4">
                <div className="flex items-center gap-4">
                  <h1 className="text-xl font-bold">Stock Market</h1>
                </div>
                <div className="flex items-center gap-4">
                  <SearchBar />
                  <LoginLogoutButton />
                </div>
              </div>
            </header>
            <div className="container mx-auto grid grid-cols-12 gap-2 px-6 py-6">
              <aside className="col-span-2">
                <NavBar />
              </aside>
              <main className="col-span-8 mx-2">{children}</main>
              <aside className="col-span-2">
                <GeneralInfo />
              </aside>
            </div>
          </AuthProvider>
        </WebSocketProvider>
      </body>
    </html>
  );
}
